### ISSUE TITLE
Request for editing in actual OSMaxx_v1.ttf & Original SVGs

### ISSUE THREAD

**Issue by cdeUG** [geometalab/osmaxx-docs#21]
Attached Zip-file containg:
a) Two  color SVGs: **education_college.svg** & **natural_rock_and_stone.svg**
_Please replace existing one (first was not the correct one / second here now without background)_

b) Two corresponding monochrom svgs: **education_college_Monoch.svg** &  **natural_rock_and_stone_Monoch.svg** 

_Only first "education_college" has to replace the existing one in OSMaxx.ttf, second "natural_rock_and_stone" is missing in current OSMaxx_v1.ttf and should be integrated

**Other instruction for OSMaxx_v1.ttf:** _Please integrate also missing SVG-Icon: destination_museum!_

Thanks! 
[OSMaxx_repl_Icons.zip](https://github.com/geometalab/osmaxx-docs/files/260182/OSMaxx_repl_Icons.zip)

**Comment by das-g** [comment]
An updated font is now on branch [`develop`](https://github.com/geometalab/osmaxx-docs/tree/develop)
- most recent [`OSMaxx_v1.ttf`](https://github.com/geometalab/osmaxx-docs/blob/develop/osmaxx-symbology/OSMaxx_point_symbols/OSMaxx_v1.ttf) on `develop` (permalink: [`OSMaxx_v1.ttf`](https://github.com/geometalab/osmaxx-docs/blob/bfad27e5347950a87457e30518c297a6b3144860/osmaxx-symbology/OSMaxx_point_symbols/OSMaxx_v1.ttf) at revision bfad27e5347950a87457e30518c297a6b3144860)

This should fix the points mentioned here. I've used the two **color** SVGs: `education_college.svg` & `natural_rock_and_stone.svg` from [OSMaxx_repl_Icons.zip](https://github.com/geometalab/osmaxx-docs/files/260182/OSMaxx_repl_Icons.zip), but converted their strokes to paths. (**FontForge doesn't handle SVGs with strokes well.** That's why some glyphs have been missing in the font before and others looked funny (too many lines) earlier this week.)

Additionally, I've eliminated one of the background circular disc glyphs (change bfad27e5347950a87457e30518c297a6b3144860): Apart from `natural_rock_and_stone.svg` (which now doesn't have any background anymore), `public_checkpoint` and `tourism_information` both had _almost_ the same circular disk as background. I've changed `tourism_information` so that they now use _identical_ circular disks as background, so we can use the same background glyph for both.

@cdeUG Please check whether the font is now OK.

**Comment by cdeUG** [comment]
@das-g I checked it already. Great work, thanks! It works well and all symbols are correctly included! Thanks also FYI on public_checkpoint and tourism_information. Good!

**Comment by das-g** [comment]
Oh, another thing I noticed: The new `natural_rock_and_stone` SVG is **gray** while the other `natural_*` icons (except for the tiny green dot for marking tree positions) are **brown**. @cdeUG, @geoSLG Is that intentional?

**Comment by cdeUG** [comment]
@das-g Yes it is intenional...thanks!
