### ISSUE TITLE
Add default icon for unknown  and update TTF

### ISSUE THREAD

**Issue by hixi** [geometalab/osmaxx-docs#3]

**Comment by das-g** [comment]
To give some context, I wrote up a quick user story for this. Feel free to tweak it:

> As a _[insert role here]_, I'd like to quickly visualize data that is not shown in the provided OSMaxx default symbology (be it data included in OSMaxx exports but not visible by default, or data I've added from another source) on top of/together with the default symbology. (So that I can see where the respective features are relative to other features.)
> 
> For point data, I need to use some symbol for that which is easily distinguishable from the point symbols already used the the default symbology.

Decision from the meeting on 2016-03-31:
One point symbol without pre-assigned semantics and unused in the provided OSMaxx symbology shall be created and included in the SVG collection and symbol font.

**Comment by cdeUG** [comment]
Attached here the whole actualized symbol collection including both parts of the new Default_OSMaxx_Marker. First to create the original svg from this, the manner Dita did untill now. (symbol is complete containing foreground and background). Foreground part  to be included in new symbol font.

[OSMaxx1_font_1_final_ug.zip](https://github.com/geometalab/osmaxx-docs/files/231283/OSMaxx1_font_1_final_ug.zip)

**Comment by hixi** [comment]
@cdeUG Thank you for your changes!

One question though: didn't we agree that changes are to be made on the single svg icons only? This way we have no idea, which symbols have changed and which ones are the same, so we would need to export all of them again.

**Comment by cdeUG** [comment]
@hixi probably only a missunderstanding. Until now when new symbols where to be included or changes has to be done, I always sent the whole collection to sfkeller by email including instructions which one were new. Up to this sfkeller gave instructions to beneditatan to create new or revised single color svg only from the required one. So you had and have always the whole actualized monochrom collection at a glace and at the adjusted size (page size for Fontforge glyphe 1000x1000mm)
In the actual case **only the monochrome icon "OSMaxx_Marker"** and the **"background_OSMaxx_marker"** had to be taken from this uploaded  collection to remake the single color symbol. I should mention that on the uploaded ZIP I didn't indicate specifically the concerning symbol, because I thought it should be clear.
But to be more clear you will find attached the two monochrome svg's "foreground_OSMaxx_marker" and "background_OSMaxx_Marker" in a ZIP. RGB color instruction are easy -> foreground: 0/0/0 & background 255/255/255.
[Default_Marker.zip](https://github.com/geometalab/osmaxx-docs/files/235154/Default_Marker.zip)
